name: Format

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  format-code:
    name: Run Prettier
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Format code
        uses: EPMatt/reviewdog-action-prettier@v1
        with:
          reporter: github-check
          level: warning
