name: Lint

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  lint-code:
    name: Run ESLint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Lint code
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-check
          level: warning
          eslint_flags: "**/*.{js,ts}"
